s = set()
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
n =int(input("Enter any number: "))
s.add(n)
print(s)